apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streamingapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
{{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
{{- else }}
    - http:
{{- end }}
        paths:
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 3001
          - path: /api/streaming
            pathType: Prefix
            backend:
              service:
                name: streaming-svc
                port:
                  number: 3002
          - path: /api/admin
            pathType: Prefix
            backend:
              service:
                name: admin-svc
                port:
                  number: 3003
          - path: /api/chat
            pathType: Prefix
            backend:
              service:
                name: chat-svc
                port:
                  number: 3004
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
