apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secrets
type: Opaque
stringData:
  jwtSecret: "{{ .Values.secrets.jwtSecret }}"
  awsAccessKeyId: "{{ .Values.secrets.awsAccessKeyId }}"
  awsSecretAccessKey: "{{ .Values.secrets.awsSecretAccessKey }}"
